version: '3'
services:
  webapp:
    image: pgconfig-api
    container_name: api.service
    labels:
      - traefik.backend=api
      - traefik.frontend.rule=Host:api.pgconfig.org
      - traefik.docker.network=proxy
      - traefik.port=8080
    ports:
      - 8080:8080
    networks:
      - proxy

networks:
  proxy:
    external: true